---
# task that adds a new user "{{docker_user}}" to the system with login shell /bin/bash
- name: Add new user "{{docker_user}}" to the system
  become: true
  become_user: root
  user:
    name: "{{docker_user}}"
    group: docker
    groups: sudo,docker
    shell: /bin/bash
  tags:
    - user
    - docker