---
# ensure /etc/docker directory exists
- name: Ensure /etc/docker directory exists
  become: true
  ansible.builtin.file:
    path: /etc/docker
    state: directory
    mode: '0755'

- name: Configure docker daemon
  become: true
  ansible.builtin.copy:
    src: files/etc/docker/daemon.json
    dest: /etc/docker/daemon.json
    mode: '0644'
  notify:
    - restart docker