---
# task that adds the public keys in ./keys to the authorized_keys file of the new user "{{ssh_user}}"
- name: Add authorized key to new user "{{ssh_user}}"
  become_user: "{{ssh_user}}"
  become: true
  authorized_key:
    user: "{{ssh_user}}"
    key: "{{ lookup('file', item) }}"
  with_fileglob: "./keys/*.pub"
  tags:
    - ssh
    - keys
    - user