# task that installs python3 on the system
---
- name: Install python3 on the system
  become: true
  apt:
    name: python3-pip
    state: present
  tags:
    - install
    - pip
    - python3
    - common