---
# task imports using the defined orders
- name: Include root_user tasks in the specified order
  include_tasks:
    file: "root_user/{{ task_order_item }}"
  loop: "{{ root_user_task_order }}"
  loop_control:
    loop_var: task_order_item
  when: root_user_task_order is defined

- name: Include ssh_user tasks in the specified order
  include_tasks:
    file: "ssh_user/{{ task_order_item }}"
  loop: "{{ ssh_user_task_order }}"
  loop_control:
    loop_var: task_order_item
  when: ssh_user_task_order is defined
