---
- name: Configure sudoers to NOPASSWD:ALL
  become: true
  become_user: root
  lineinfile:
    path: /etc/sudoers.d/sudoers-nopasswd.conf
    line: '%sudo ALL=(ALL) NOPASSWD:ALL'
    validate: 'visudo -cf %s'
    state: present
    backup: yes
    mode: '0440'
    owner: 'root'
    group: 'root'
    create: yes
  tags:
    - sudo