# task that installs docker
---
- name: Install Docker and docker-compose
  become: true
  apt:
    name: 
      - docker.io
      - docker-compose
    state: present
  tags:
    - docker
    - install